#!/bin/bash


export TB_HOME=$(pwd)
export RISCV_GNU_TOOLCHAIN_INSTALL_PREFIX=/opt/riscv

echo TB_HOME: $TB_HOME
echo RISCV_GNU_TOOLCHAIN_INSTALL_PREFIX: $RISCV_GNU_TOOLCHAIN_INSTALL_PREFIX

alias tb='$TB_HOME'
